### ISSUE TITLE
Data gathering for iOS device traffic invisible to Bermuda

### ISSUE THREAD

**Issue by agittins** [agittins/bermuda#375]
This issue is to (hopefully) gather data from people who can capture iOS BLE traffic at times when Bermuda considers the device to be `AWAY` or `UNAVAILABLE`.

The operating theory is that these devices *might* be sending identifiable traffic, but the habluetooth lib [might be filtering](https://github.com/Bluetooth-Devices/habluetooth/blob/306c460a4bbc86286820c22757208fd85b5e56b9/src/habluetooth/manager.py#L448) it out, making the device invisible to Bermuda.

If you've managed to save some data from iOS broadcasts while Bermuda considered the device "away", please upload the saved file here, and optionally, include some screenshots if they're interesting, and any comments if things were noteworthy (eg, "I think the data at 01:32:45 was when I opened my airpods case..")

Thanks!

Post to the HA community group:

# Help with analysing iPhone traffic

Howdy all - I am interested in seeing if we can do better with spotting iPhones. The HA bluetooth library does a bit of filtering on certain apple traffic, and I am wondering if it is causing Bermuda to not be able to see iPhones at times when they are actually transmitting.

Unfortunately, the only iOS devices I have here are older ones, and they are annoyingly rock-solid at being detected.

If you have:
- at least one iOS device that should be always visible, but Bermuda often shows as `away` or `unavailable`
- another phone/tablet that can run NRFConnect or similar
- a bit of time to stuff around

then perhaps you could help! :slight_smile: 

What I would like to see is if there is any BLE traffic being sent by an iOS device at a time that Bermuda thinks it's away. In NRFConnect, the "More" screen gives a graph of adverts, colour-coded by content, and below that a summary of the adverts as they change over time. You can then hit the three-dots, Save, and choose "Save to file". If you could gather that and forward the data to me, we might be able to find more reliable ways to track iOS devices when they go into their various power-saving modes. Or not - at this stage it's just a theory without supporting data.

# User reports of iOS transmit outages

Issue #369 
- Recent iPhone?
- Mainly happens on arriving home, BT adverts don't start for perhaps 15 minutes
- Suspect possible interaction with not transmitting until after home wifi is active?

Issue #385, #323 
- Iphone 15, iPhone 15PRO
- iOS 18.0.1 (both)
- Daytime usually OK, outages between ~ 9PM and 1AM.

# Potential fixes
- Install the Room Assistant App, as it sends BLE broadcasts
- Install a COVID19 exposure tracking app, as they seem to be able to transmit reliably
- An iOS setting "Auto-toggle visibility" being turned *off* may improve things. Unclear where this setting is or how it's accessed or enabled. Perhaps an app needs to be granted location permissions first, then it shows up in this list? Not sure.

The [espresence docs](https://espresense.com/beacons/apple) state:
> Note: Some iOS devices do not emit a beacon while the phone screen is off if there is not a reason for the device to broadcast a signal, consequently the device may not appear while the screen is off. Something like an iWatch, Universal Clipboard with Handoff enabled, or other services that require the phone to communicate regularly may resolve this issue as they require the subject iOS device to communicate while ‘sleeping’. In the case you do not have a bluetooth device like an iWatch, some people report that using background apps like iCloud Family Sharing, iCloud Photo Backup, or Room Assistant have convinced the device to communicate while ‘sleeping’. This issue is not universal, but it’s not clear why this occurs at this time and you may not experience this issue even if the device seemingly has no reason to communicate.

**Comment by agittins** [comment]
Hi All! I found a bug in Bermuda related to IRK advertisements that only showed up after my Pixel 6Pro updated to Android15. The device started to go `Unknown` for long periods shortly after an address change.

It turned out that Android now runs more than one active IRK MAC address at a time, but Bermuda was only listening for the most-recently-new address. This is fixed in v0.8.5-rc1.

I am hopeful that this is the root cause of the iOS issue as well, but as I don't have any Apple devices new enough for that OS I'm unable to test it.

If anyone who has been experiencing this issue and can try out v0.8.5-rc1 to test could let me know their experience that would be awesome! I am going to close all related issues and direct them all to the master tracking issue for iOS traffic outages, at #375 - it would be great if you could submit your feedback (and diagnostics files, if possible) there for this issue, or raise a new issue if you are experiencing other difficulties. Cheers!

**Comment by rickt123** [comment]
Hello @agittins I installed v0.8.5-rc1 this morning and I'm not sure if it's better or not.  Still seeing a lot of unknowns in the area sensor.  

![Image](https://github.com/user-attachments/assets/d1ce5427-3c0b-403a-af69-19b24b5973f5)

[home-assistant_bermuda_2025-04-16T11-29-26.872Z.log](https://github.com/user-attachments/files/19776519/home-assistant_bermuda_2025-04-16T11-29-26.872Z.log)

[config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY (4).json](https://github.com/user-attachments/files/19776524/config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY.4.json)

[action bermuda.dump_devices_4.16.2025.txt](https://github.com/user-attachments/files/19776542/action.bermuda.dump_devices_4.16.2025.txt)

**Comment by rickt123** [comment]
Hi @agittins, installed v0.8.0 this morning and so far much more stable.  Unfortunately I can only test it with two phone right now, but as you can see no where near the bounce I saw before.  I'll keep running it and let you know of any major hiccups.  Thanks for all of the hard work!

![Image](https://github.com/user-attachments/assets/6b90f788-dfb5-4695-a4de-0df5ada85dfe)

[config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY (5).json](https://github.com/user-attachments/files/19866837/config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY.5.json)
[home-assistant_bermuda_2025-04-23T11-49-26.442Z.log](https://github.com/user-attachments/files/19866836/home-assistant_bermuda_2025-04-23T11-49-26.442Z.log)

[action bermuda.dump_devices_4.23.2025.txt](https://github.com/user-attachments/files/19866847/action.bermuda.dump_devices_4.23.2025.txt)

**Comment by jksmurf** [comment]
Right, thank you for the udpate and my feedback as requested.

- My circuit, 5 Trackers vs an iphone13 and and an ipad Air3
- On first install I thought "you've nailed it". the iPad changed rooms and recogniosed the right one faster than the iPhone 13, incredibly good.
- Went to do a second round and the Air3 was up to it's Unknown tricks. Logs attached.

[home-assistant_bermuda_2025-04-23T13-07-16.554Z.log](https://github.com/user-attachments/files/19869144/home-assistant_bermuda_2025-04-23T13-07-16.554Z.log)

**Comment by agittins** [comment]
@rickt123 glad to see it looks a lot better for you, but an extra special thanks for the diagnostics! That just helped me track down a new bug(!) that otherwise would have taken me **ages** to work out! Well, it's a bug I already had noted down, but I didn't know it was going to present like this, and my intended fix may have just hidden it instead of fixing it.

I've just pushed v0.8.1 which includes the fix for this over-eager pruning, which should certainly fix the issue your iPhone16 had at 7:10, and hopefully will address similar symptoms.

@jksmurf @rccoleman I am hopeful this will improve your situation also, especially given the apparent periodic nature of yours, Rob.

**Comment by jksmurf** [comment]
>pushed v0.8.1 which includes the fix for this over-eager pruning, which should certainly fix the issue your iPhone16 had at 7:10, and hopefully will address similar symptoms.
> 
> [@jksmurf](https://github.com/jksmurf) [@rccoleman](https://github.com/rccoleman) I am hopeful this will improve your situation also, especially given the apparent periodic nature of yours, Rob.

Hiya, right, first off you’re amazing keeping at this, really appreciate it.

Unfortunately my iPad is either one lazy piece of silicone or Bermuda might need a further tweak.
Oddly, again, when I first installed the v0.8.1 update, the iPad showed a location. Briefly. Pics are from that phase, not when it goes Unknown, which should be apparent in the logs.

As soon as I hit debugging mode, it went unknown and stayed there for the circuit. I only took the phone and iPad, watch stays in the master bedroom.

As before, phone changes beautifully; iPad, not so much. Thanks again!

![Image](https://github.com/user-attachments/assets/0ccc11c2-ccaf-4235-bf72-6622baa668d3)
![Image](https://github.com/user-attachments/assets/f61e3f44-cca8-44b6-a63e-de17161733d8)
![Image](https://github.com/user-attachments/assets/ccf670f1-5f24-4265-ae46-11681e42d455)
![Image](https://github.com/user-attachments/assets/8bfe6a07-a5f6-4a3d-8542-3d6c905f1403)
![Image](https://github.com/user-attachments/assets/a4a6e3f1-6d51-4208-85ab-c482b93e202a)

[home-assistant_bermuda_2025-04-23T22-54-40.326Z.log](https://github.com/user-attachments/files/19876677/home-assistant_bermuda_2025-04-23T22-54-40.326Z.log)

**Comment by rickt123** [comment]
Hi @agittins glad to help where I can.  I've installed v0.8.1 around 6:50 PM EDT can noticing unknowns showed up quicker than before.  

[config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY (5).json](https://github.com/user-attachments/files/19876737/config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY.5.json)
[home-assistant_bermuda_2025-04-23T23-09-29.456Z.log](https://github.com/user-attachments/files/19876736/home-assistant_bermuda_2025-04-23T23-09-29.456Z.log)

[bermunda_device_dump_4.23.2025_19.15.txt](https://github.com/user-attachments/files/19876780/bermunda_device_dump_4.23.2025_19.15.txt)

**Comment by rccoleman** [comment]
Here's my debug log and device dump.

[Bermuda device dump.txt](https://github.com/user-attachments/files/19880848/Bermuda.device.dump.txt)
[home-assistant_bermuda_2025-04-24T01-45-12.560Z.log](https://github.com/user-attachments/files/19880849/home-assistant_bermuda_2025-04-24T01-45-12.560Z.log)

And the history, with the Bermuda device_tracker entity on top and the private BTLE device_tracker on the bottom:

<img width="545" alt="Image" src="https://github.com/user-attachments/assets/cdba6928-79dc-47e0-8277-d78ea3a3fb72" />

**Comment by rickt123** [comment]
Good morning here are the logs from overnight.

[home-assistant_bermuda_2025-04-24T10-20-21.481Z.log](https://github.com/user-attachments/files/19889426/home-assistant_bermuda_2025-04-24T10-20-21.481Z.log)
[config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY (6).json](https://github.com/user-attachments/files/19889425/config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY.6.json)

**Comment by rickt123** [comment]
Hey @jksmurf, there is a good way to expect the device dump, what I did was click on the first line in the response window, scroll all the way down, shift click on the last character in the last night, that should highlight everything can then a ctrl C and ctrl V into a text file.  As for the json file, when looking at the Bermuda integration, click the 3 dots and then download diagnostics.

**Comment by jksmurf** [comment]
> Hey [@jksmurf](https://github.com/jksmurf), there is a good way to expect the device dump, what I did was click on the first line in the response window, scroll all the way down, shift click on the last character in the last night, that should highlight everything can then a ctrl C and ctrl V into a text file. As for the json file, when looking at the Bermuda integration, click the 3 dots and then download diagnostics.

Great thanks.

@agittins I have done anotther round just now, this time capturing, hopefully the full set of data., HTH.

[home-assistant_bermuda_2025-04-25T01-49-01.557Z.log](https://github.com/user-attachments/files/19901569/home-assistant_bermuda_2025-04-25T01-49-01.557Z.log)
[config_entry-bermuda-01JQQM6915K6A9WD8KWG9C95V5.json](https://github.com/user-attachments/files/19901567/config_entry-bermuda-01JQQM6915K6A9WD8KWG9C95V5.json)
[Device_Dump.txt](https://github.com/user-attachments/files/19901568/Device_Dump.txt)
[history.csv](https://github.com/user-attachments/files/19901570/history.csv)
![Image](https://github.com/user-attachments/assets/59e6747c-8677-42eb-9403-bfa40276aee8)

**Comment by agittins** [comment]
Hi folks...

> [!IMPORTANT]
> There might be a bug where iOS devices go "unknown" *specifically* when they have the HA Companion app open and foregrounded. If that sounds like you and you can verify the outcome on your device, please subscribe to #544 and comment with which of your iOS devices do and don't suffer from it, and their iOS and HA Companion versions. Thanks!

For cases where the iOS device goes unknown for periods but does not seem to be related to having the HA companion app running in the foreground at those times, this issue here is the one to continue tracking.

**Comment by agittins** [comment]
Gah... this draft was in one of my open tabs (I've only a few hundred of those, what could possibly go wrong?) so it's a bit out-of-time, but might be of use...

"Download diagnostics" includes the full output of the `bermuda.dump_devices` and more, so it's much easier to just include the results of download diagnostics rather than trying to copy/paste the dump_devices, which can be a bit tricky. 

@jksmurf re your latest esphome yaml files...

For completeness I'd suggest:
- I'd remove the `captive_portal:` as it uses a fair amount of RAM via the webserver, as I understand it (I could be wrong on that though)
- setting `continuous: True` should be `False` in `esp32_ble_tracker`, so that the automation in the `api:` section can delay the start of scanning until after the api is connected. But.. it shouldn't affect on-going operation, so isn't likely the root of your issues (unless the proxies are rebooting)
- that said, from your last diagnostic it looks like all your proxies are healthy and working well, now.

**Comment by jksmurf** [comment]
> 
> [@jksmurf](https://github.com/jksmurf) re your latest esphome yaml files...
> 
> For completeness I'd suggest:
> 
> * I'd remove the `captive_portal:` as it uses a fair amount of RAM via the webserver, as I understand it (I could be wrong on that though)
> * setting `continuous: True` should be `False` in `esp32_ble_tracker`, so that the automation in the `api:` section can delay the start of scanning until after the api is connected. But.. it shouldn't affect on-going operation, so isn't likely the root of your issues (unless the proxies are rebooting)
> * that said, from your last diagnostic it looks like all your proxies are healthy and working well, now.

Cheers Ash I’ll have a dekko at those sometime but if it’s not causing too much havoc it’ll be lower order priority for the moment :-).

**Comment by agittins** [comment]
> Cheers Ash I’ll have a dekko at those sometime but if it’s not causing too much havoc it’ll be lower order priority for the moment :-).

No worries, yeah they're not causing any serious issues, your proxies appear to be performing quite well regardless. 👍🏼

**Comment by agittins** [comment]
v0.8.2-beta3 has changes which will hopefully make a significant difference for this issue. If y'all could try it out and let me know that would be great. A diagnostics during/after an `unknown` episode (if there are any) would be very helpful.

**Comment by agittins** [comment]
Thanks @bravotangoau that's great to hear!

**Comment by jksmurf** [comment]
Seems to be rock solid for me too, thus far. Great work @agittins! 🙏

**Comment by agittins** [comment]
Awesome!

FYI v0.8.2 that I just released doesn't have any changes, it's exactly the same as beta3, just decided to cut a full release since it's looking like a good waypoint.

**Comment by RN-Say** [comment]
I'm having a mixed result. My iphone 13pro is great (best ever). My wife's iphone 14pro is still only available for brief intervals when she is interacting with her phone. I struggle to figure out what makes them different. 

I have added room assistant to her phone.
I bought an airtag and paired it with her phone. 
We both have ipads, though her's is older.
I bought 2 mitags(one for each floor) and paired them to her phone using the isearching app. 
We both have garmin watches paired to garmin connect on the phone. I wear mine constantly and she only wears occasionally.
I use airpods connected by bluetooth and she does not. (thinking of buying her a pair now)

**Comment by rickt123** [comment]
Hey @agittins 

This release has been working extremely well, fantastic job!  Extremely stable, main observation is the area reporting sometimes when sitting in one room without touching the room Bermuda consistently reports being in that room, but pick up the phone it will sometimes move to another sensor for a few seconds or up to minutes in some cases.  I think this is more related my configs, sensor placement, etc.  I'll keep investigating that.  However my problematic iPhone 16 continues to have very mixed results, may be phone specific but I captured (hopefully) the diagnostics before it changed to unknown and during the unknown event.  

Thanks again @agittins 

[config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY-during.json](https://github.com/user-attachments/files/20365916/config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY-during.json)
[config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY-before.json](https://github.com/user-attachments/files/20365917/config_entry-bermuda-01JJCTTVD25N2MSMTC9RNG74NY-before.json)

**Comment by agittins** [comment]
Hey @rickt123 - I removed your diags because they included information that should have been redacted. I'm really sorry about that, and I've released v0.8.3 which fixes the issue 😰 Please feel free to contact me at ash@ajg.net.au if you have any concerns.

Taking a look at said diagnostics, at the time the "during" diags were taken, your phone was showing as being in the Kitchen area.

```
======== Device Detail for "apple - iphone16 - rick" [ff0c::IRK_DEV_87] =============

 Scanner/Time (T0 = 566973.76)   T0  T-1  T-2  T-3  T-4  T-5  T-6  T-7  T-8  T-9 T-10
=====================================================================================
esphome - bedroom(plus one)    31.6    - 20.0    -    -    -    -    -    -    -    -
esphome - bedroom(plus one)2   12.6  6.3  6.3    - 20.0 22.4    -    - 17.8 15.8 17.8
esphome - office light            - 44.7    -    -    -    - 89.1    -    -    -    -
esphome - bedroom(mine)           -  5.0  5.6 17.8 22.4 28.2    - 11.2 11.2 11.2 14.1
esphome - living room2          5.0 17.8 22.4 20.0  8.9  7.9 10.0 10.0 17.8 22.4
esphome - bedroom(mine)2          -  8.9 17.8    - 22.4 20.0    - 17.8 39.8 22.4 20.0
esphome - kitchen              12.6 11.2    - 14.1    - 31.6 17.8    - 28.2 17.8 28.2
esphome - bedroom(bry)         35.5 44.7 17.8 20.0    - 25.1 44.7    - 25.1    - 22.4
esphome - bedroom(rachel)       6.3 12.6  5.6  7.9 22.4 14.1 22.4    -    - 15.8    -
esphome - living room           5.0  5.0  4.0    -  7.9  8.9  7.1  7.9  7.9  4.0 10.0
esphome - kitchen2                -  1.6  1.4  1.4  1.6  2.2  2.2  2.2  2.2  2.2  2.0
esphome - office                  - 39.8    - 44.7    -    -    - 70.8    - 56.2    -
```

This table shows the 10 seconds prior to creating the diags, and indicates the raw distance for each advert received by each scanner in that interval. Kitchen2 looks like it should have been the area "winner" for this entire time period.

```
============= Hist-by-interval for "apple - iphone16 - rick" [ff0c::IRK_DEV_87] =============

                       Scanner ->      [Device MAC]             Smoothed Distances by second (newest ---> oldest)

   esphome - bedroom(plus one) -> [4a::OTHER_MAC_52::ba]  20.0  20.0  20.0  20.0  20.0  20.0  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1
  esphome - bedroom(plus one)2 -> [4a::OTHER_MAC_52::ba]   6.3   6.3   6.3   6.3   6.3   6.3  20.0  20.0  20.0  20.0  22.4  22.4  17.8  17.8  17.8  17.8  17.8  17.8  15.8  15.8
        esphome - office light -> [4a::OTHER_MAC_52::ba]  44.7  44.7  44.7  44.7  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1  50.1
       esphome - bedroom(mine) -> [4a::OTHER_MAC_52::ba]   5.0   5.0   5.0   5.0   5.6   5.6  17.8  17.8  22.4  22.4  11.2  11.2  11.2  11.2  11.2  11.2  11.2  11.2  11.2  11.2
        esphome - living room2 -> [4a::OTHER_MAC_52::ba]   5.0   5.0  17.8  17.8   7.9   7.9   7.9   7.9   7.9   7.9   7.9   7.9  10.0  10.0  10.0  10.0  17.8  17.8  22.4  22.4
      esphome - bedroom(mine)2 -> [4a::OTHER_MAC_52::ba]   8.9   8.9   8.9   8.9  17.8  17.8  22.4  22.4  22.4  22.4  20.0  20.0  17.8  17.8  17.8  17.8  22.4  22.4  22.4  22.4
             esphome - kitchen -> [4a::OTHER_MAC_52::ba]  12.6  12.6  11.2  11.2  14.1  14.1  14.1  14.1  17.8  17.8  17.8  17.8  17.8  17.8  17.8  17.8  17.8  17.8  17.8  17.8
        esphome - bedroom(bry) -> [4a::OTHER_MAC_52::ba]  35.5  35.5  17.8  17.8  17.8  17.8  20.0  20.0  25.1  25.1  25.1  25.1  25.1  25.1  25.1  25.1  25.1  25.1  22.4  22.4
     esphome - bedroom(rachel) -> [4a::OTHER_MAC_52::ba]   6.3   6.3   5.6   5.6   5.6   5.6   7.9   7.9  14.1  14.1  14.1  14.1  22.4  22.4  15.8  15.8  15.8  15.8  15.8  15.8
         esphome - living room -> [4a::OTHER_MAC_52::ba]   5.0   5.0   5.0   5.0   4.0   4.0   7.9   7.9   7.9   7.9   7.1   7.1   7.1   7.1   7.9   7.9   4.0   4.0   4.0   4.0
            esphome - kitchen2 -> [4a::OTHER_MAC_52::ba]   1.6   1.6   1.6   1.6   1.4   1.4   1.4   1.4   1.6   1.6   2.2   2.2   2.2   2.2   2.2   2.2   2.2   2.2   2.2   2.2
              esphome - office -> [4a::OTHER_MAC_52::ba]  39.8  39.8  39.8  39.8  44.7  44.7  44.7  44.7  56.2  56.2  56.2  56.2  56.2  56.2  56.2  56.2  56.2  56.2  56.2  56.2

```

This shows the last 20 seconds, with the "smoothed" distances for each scanner for your iphone. This also looks like Kitchen2 was the clear winner for this entire duration. That said, the living room(1) proxy up until 17 seconds ago was under 4m away and kitchen2 was more like 2.5m. It's possible that the phone may have been showing in living room previously, but might not have switched to kitchen until the difference was substantial enough to switch, but everything up to 20 seconds ago was certainly strong enough for kitchen to become the area.

What area did your phone switch from and to in this case? Do you think it was within the 10 seconds / 20 seconds of the history available in the diags?

**Comment by rickt123** [comment]
Hey @agittins 

Thanks for the analysis and I feel horrible, the problem phone is Apple - iPhone - Plus.  It's the only phone in the house that isn't the pro version and that may be the overall problem.  Attached is the history for that phone when I capture the diagnostics.  In the meantime I'll install v0.8.3.

Rick

[Apple - iPhone - Plus history 5.21.2025.5a - 7a.csv.xlsx](https://github.com/user-attachments/files/20398195/Apple.-.iPhone.-.Plus.history.5.21.2025.5a.-.7a.csv.xlsx)

**Comment by mysciencefriend** [comment]
Hi @agittins, thanks so much for all of your hard work on this project, it's so useful.  I've had the 'iphone toggling to unavailable' issue for a while now, but I just stumbled across this thread after reading the change log for the newest 0.8.2, but still experiencing this issue after upgrading.  

I did just discover one observation which might be helpful... I looked at the home assistant history for both my iphone and my wife's iphone and noticed that both our devices go unavailable at exactly the same time, which suggests to me the issue might not be on the phone itself.  The screenshot below is a sample of 3 hours, and you can see despite the fact that we are in different parts of the house and connected to different sensors, the 'unavailable' grey bars are perfectly synched.  Just for context, the top two bars in the screenshot are the bermuda room location sensor entities, and the bottom one is the bermuda device_tracker entity for my iphone.  I forgot to turn logging back on for my wife's device_tracker entity, but I assume it would also line up with her room location sensor entity.

Hopefully this is useful... if there's any additional info or logs I can provide please let me know.

![Image](https://github.com/user-attachments/assets/dc953b95-a211-4c0a-821e-d43bc6ef826f)

**Comment by agittins** [comment]
Hi @mysciencefriend - yes, I think your issue is the one raised in #579 - `unavailable` is distinct from `unknown`, which can be a bit confusing!

**Comment by mysciencefriend** [comment]
> Hi [@mysciencefriend](https://github.com/mysciencefriend) - yes, I think your issue is the one raised in [#579](https://github.com/agittins/bermuda/issues/579) - `unavailable` is distinct from `unknown`, which can be a bit confusing!

Ahhh makes sense, apologies for cluttering up this thread!  Come to think of it, my iPhones haven’t seemed to have gone to “unknown” since I upgraded, so it looks like at least that issue appears to be solved!  Thanks so much again for all the great work on this project! I had been using the “monitor” project before for presence sensing, but Bermuda is way less brittle than that was.

**Comment by agittins** [comment]
> Thanks so much again for all the great work on this project! I had been using the “monitor” project before for presence sensing, but Bermuda is way less brittle than that was.

Great that it's working for you! And cheers - we have the advantage of placing Bermuda on top of all the amazing work done by the ESPHome and HA teams, which makes Bermuda's part of things so much easier to implement!

**Comment by tylerhartwig** [comment]
@agittins either 0.8.5 beta 1 or 2 fixed any remaining issues I saw after 0.8.4 it seems. I installed 2 today, never tried 1
