### ISSUE TITLE
Area entities & distances become unavailable after adding new scanners

### ISSUE THREAD

**Issue by kbrohkahn** [agittins/bermuda#560]
## Configuration

With new scanners

![Image](https://github.com/user-attachments/assets/ddbadb58-6077-47e0-b7d5-d4b8c82c7f60)

![Image](https://github.com/user-attachments/assets/9bfd661f-19d3-4545-bd01-67e3d6eb9d4f)

![Image](https://github.com/user-attachments/assets/06845395-b670-4b6a-be99-948e09b1b621)

Without new scanners

![Image](https://github.com/user-attachments/assets/38aaad89-a091-4501-ab95-5e96120da366)

![Image](https://github.com/user-attachments/assets/2808d3c7-2658-41d8-8c24-99a6028af132)

![Image](https://github.com/user-attachments/assets/9feb1e16-8586-492a-800b-de94b96f4297)

![Image](https://github.com/user-attachments/assets/5463d6ae-8261-48bf-a4e9-2deec032c2b6)

## Describe the bug

Hi, I am trying to add new scanners to an existing Bermuda setup and have run into an issue. In summary, when the new scanners are included in the Bermuda configuration by adding the EspHome Bluetooth devices to Home Assistant, the Bermuda area entities become unavailable. It seems like Bermuda is somehow caching the initial scanners used and won't have area detection when new scanners are added.

I previosly had 5 scanners and wanted to add 2 more for a little more accuracy. It may be worth noting that the scanners (arduino esp32dev) are a different type of my prior 5 (esp-idf esp32dev and everything-presence-one devices). The new devices had no issues installing ESPHome and getting added to Home Assistant as ESPHome devices and Bluetooth devices, which Bermuda automatically recognized.

I did get the initial Bermuda notification saying that the new devices did not have an area and it would need to be set, so I did for both the ESPHome and bluetooth devices. But when I checked Bermuda, all of the tracked bluetooth devices' area entity became unavailable as Bermuda would no longer provide it. I have tried everything I could think of

- Triple checked the 2 new devices (both ESPHome and Bluetooth) for the correct areas
- Reloaded the Bermuda integration
- Stopped Home Assistant, deleted the .storage/bluetooth* files, and restarted
- Removed the Bermuda integration, restarted Home Assistant, deleted the Bermuda custom component, restarted, installed the component, restarted, added the integration
- Deleted all the ESPHome devices in Home Assistant, restarted, added them all back

And I keep getting the same results. What's interesting is that at any point, if I remove the new ESPHome devices from Home Assistant, Bermuda works as expected and the area entities are populated. But as soon as I put the new devices back in, the area entities stop working. The device_tracker entities never seem to have any issue, but the area and distance entities do not work when I try to include the new scanners.

## Diagnostics
Attached

[config_entry-bermuda-01JTPR3B7R5SA0X2791MQ3D69X.json](https://github.com/user-attachments/files/20095589/config_entry-bermuda-01JTPR3B7R5SA0X2791MQ3D69X.json)

**Comment by agittins** [comment]
Hmm that's no good (I like your theme though!). I'm taking a look at your diags...

@faz17 could you do a "Download Diagnostics" in Bermuda and attach it here?

**Comment by faz17** [comment]
The error was yesterday 07/05 at 12:33

[config_entry-bermuda-01JD28JHY3NW2H3QR72X5WC9TS.json](https://github.com/user-attachments/files/20098504/config_entry-bermuda-01JD28JHY3NW2H3QR72X5WC9TS.json)

**Comment by agittins** [comment]
I've just pushed v0.8.2-beta1 to see if it resolves your issues. It includes some fixes around pruning old addresses that might be causing your problems.

If you could try it out that would be great - you might need to configure HACS to enable pre-release versions.

**Comment by faz17** [comment]
I've installed the new version. Let's see how it goes

**Comment by kbrohkahn** [comment]
I tried the new version and got the same issue. Interestingly, it's only one of the new scanners now. With my "theater-bluetooth-proxy" added the area doesn't work, but removing that ESPHome device fixes the issue. I tried changing the device names but that didn't help. Not sure what's going on because this device is essentially identical to another one that works and scans fine.

**Comment by kbrohkahn** [comment]
Well, it's working now. I reinstalled ESPHome with the same configuration on the errant scanner, and the scanner and all entities are working properly now. Maybe it was something wrong with ESPHome

**Comment by faz17** [comment]
@agittins The problem still persists

![Image](https://github.com/user-attachments/assets/3f252e1c-bef9-4f0f-b47d-2c2e5da97cf0)

**Comment by DanielHabenicht** [comment]
I think I have the same problem. I am currently writing my own bluetooth proxy based on ESPHome for a Raspberry and as soon as I add it the Entities become unavailable. 
As long as the Bluetooth Proxy is present in Home Assistant, even on reload no entities a are generated for Area tracking.

**Comment by DanielHabenicht** [comment]
> [@DanielHabenicht](https://github.com/DanielHabenicht) that's very interesting! Are you implementing a BaseHaRemoteScanner with the pi?

I am implementing the ESPHome native API and use `BluetoothLeAdvertisementResponse` Proto Object like this: https://github.com/UbiHome/UbiHome/blob/11abd14e44cf79757bb1bda74a9f5c6f3ff68c58/components/api/src/lib.rs#L303
I don't know what it is mapped to inside HomeAssistant but it's already displaying many messages in the advertisement-monitor (as well as the one from my garmin)

**Comment by kbrohkahn** [comment]
I've been confused as well. I had 2 proxies using the same hardware and flashed them with ESPHome at the same time, a few minutes apart. The only visual difference I configured was the device name. One worked with Bermuda, one did not. All I did to fix the issue was re-flash the one that did not work. It's still on the 2025.4.1 firmware so I don't think the version changed.

**Comment by faz17** [comment]
@agittins i'm using only shelly and the native Raspberry bluetooth and i don't add anything to home assistant. I don't know how to replicate because It became not available Suddenly

**Comment by bravotangoau** [comment]
@faz17 I'm using all Shellys too and I've found that you only need two settings to get them to work:
1) In Shelly's Network settings, just enable bluetooth. Don't need to enable RPC.
2) In HA's Shelly integration, click "configure" on each entry of the Shelly devices and select "Active" in Options. 
3) Of course, assign each Shelly to an area. 
That's basically all you need.

**Comment by faz17** [comment]
@agittins i attach this screenshot if It can be helpful

![Image](https://github.com/user-attachments/assets/a3d9bc17-d6db-4761-b74f-b76914e81bf9)

**Comment by agittins** [comment]
Hi all,

I've done a pretty substantial re-write on how Bermuda finds and iterates over scanners, how it creates the distance sensors and how it gathers and processes the advertisements.

If you could try out v0.8.2-beta2 which I released today I'd be interested to know how it goes for you. I am hopeful that the weird "add one more scanner and it all stops" thing is resolved by this, as it involved a lot of cleaning up and streamlining. 🤞🏼

**Comment by DanielHabenicht** [comment]
I can confirm its working for me with with `v0.8.2-beta2`. Thank you very much!

**Comment by faz17** [comment]
Just installed the new version. Let's see how it goes. Thanks!

**Comment by agittins** [comment]
@DanielHabenicht 
> One thing I can consistently reproduce is that new bluetooth proxies do not seem to generate any debug sensors (Unfiltered/Distance to 'Proxy') or they are Unavailable.

Could you give me a bit more detail on this? I am unsure of the process and outcome that you mean specifically. I expected most of this sort of issue to be fixed now with beta2, but quite possible I've missed something else that isn't cropping up for me in my typical workflow.

**Comment by DanielHabenicht** [comment]
@agittins 
> Could you give me a bit more detail on this? I am unsure of the process and outcome that you mean specifically. I expected most of this sort of issue to be fixed now with beta2, but quite possible I've missed something else that isn't cropping up for me in my typical workflow.

Sure, sorry for being so unspecfic. 
1. I have the following Proxies: 

![Image](https://github.com/user-attachments/assets/16467bb8-2462-4ee2-856b-9658ae4a5a23)

2. But only these Sensors:

![Image](https://github.com/user-attachments/assets/d6123aa4-c849-4e82-8b53-f013e7fd0712)

So its missing the sensors for the magicmirror2?

**Comment by agittins** [comment]
@DanielHabenicht interesting. Is it always/only that particular proxy that Bermuda doesn't create the distanceto sensors for? What is that scanner running - is it your UBIHome raspi? (a very cool project, by the way!)

If it's (always) an ubihome device, can you open a new issue, and include a "download diagnostics", and if possible, debug logging from Bermuda while doing a "reload" of Bermuda, and 20 seconds or so thereafter? Bermuda is likely making assumptions about what a scanner should look like, and those assumptions might be wrong for an UBIHome. I'm happy to fix Bermuda's logic to support it.

Note that the debug log contains full MAC addresses, IPs etc, so you might want to only supply a diags for starters, or email me the logs at ash@ajg.net.au - whatever you're comfortable with. The diags are redacted for MAC addresses, Beacon id's and IRKs.
